[mypy]
python_version = 3.12
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_reexport = True
mypy_path = dags
namespace_packages = True
explicit_package_bases = True

[mypy-fastembed.*]
ignore_missing_imports = True

[mypy-langchain_text_splitters.*]
ignore_missing_imports = True

[mypy-pgvector.*]
ignore_missing_imports = True

[mypy-testcontainers.*]
ignore_missing_imports = True
